#!/bin/bash

# Script to randomly set Background from files in a directory

# Directory Containing Pictures
DIR="/home/ash/Desktop/Wallpapers_Slideshow"

# Command to Select a random jpg file from directory
# Delete the *.jpg to select any file but it may return a folder
PIC=$(ls $DIR/*.jpg | shuf -n1)
#echo $PIC
# Command to set Background Image
#gconftool -t string -s /desktop/gnome/background/picture_filename $PIC
echo "gsettings set org.gnome.desktop.background picture-uri \"file://"$PIC"\""
#gsettings set org.gnome.desktop.background draw-background false
#gsettings set org.gnome.desktop.background picture-uri "\"file://"+$PIC+"\""
gsettings set org.gnome.desktop.background draw-background true
gsettings set org.gnome.desktop.background picture-uri "\"file://"+$PIC+"\""
gsettings set org.gnome.desktop.background picture-uri "\"file://"+$PIC+"\""
